Increment
icyrogue/ya-sher pull request #1
Opened 2022-07-03 17:54 UTC by icyrogue

2022-07-04 18:22 UTC, bambruysk reviewed
Убрать лишний файл main_test 
Разместить по пакетам ( apihandlers, usecase, storage) 
Пакеты в internal

2022-07-04 18:22 UTC, bambruysk commented on handlers/handlers.go
> +// Create short version from long one
Комментарий должен начинаться с имени метода.

2022-07-04 18:22 UTC, bambruysk commented on handlers/handlers.go
> +func CrShort() gin.HandlerFunc {
Нужно покрыть эти хендлеры тестами отдельно от мейна

2022-07-04 18:22 UTC, bambruysk commented on handlers/handlers.go
> +var urls = make(map[string]string)
это хранилище url можно вывести это в отдельный пакет с интерфйесом CRUD ( типа Crreate, Get, Update Delete)  лучше сделать это раньше

2022-07-04 18:22 UTC, bambruysk commented on handlers/handlers.go
> +func ReLong() gin.HandlerFunc {
Эти методы лучше привзяать к некотолрой структуре handlers

2022-07-04 18:22 UTC, bambruysk commented on handlers/handlers.go
> +			fmt.Println(err)
Лучше логгировать пакетами log или zap

2022-07-04 18:22 UTC, bambruysk commented on handlers/handlers.go
> +			fmt.Println(err)
Случилась ошибка, стоит ли продолжать?

2022-07-04 18:22 UTC, bambruysk commented on cmd/shortener/main.go
> +func apiInit() *gin.Engine {
тоже стоит вынести в отдельный пакет

2022-07-04 18:22 UTC, bambruysk commented on IdGen/genid.go
> +func GenID(data string) string {
Здесь как и везде возможны коллизии, генерация одного и того же ключа. Как с этим бороться?

2022-07-04 18:22 UTC, bambruysk commented on cmd/shortener/main_test.go
> +			defer res.Body.Close() //<-- Иначе автотест ругается
И правильно ругается. Всегда надо закрывать))

2022-07-04 18:22 UTC, bambruysk commented on handlers/handlers.go
> +	idgen "github.com/icyrogue/ya-sher/IdGen"
называние пакета не Go-way нужно назвать idgen

2022-07-10 06:18 UTC, bambruysk requested changes
Поправить эти гнебольшие замечения и можно будет сливать.

2022-07-10 06:18 UTC, bambruysk commented on internal/api/api.go
> +type URLProcessor interface {
Этот интерфейс у нас нигде кажется не используется. Можно убрать

2022-07-10 06:18 UTC, bambruysk commented on internal/api/api.go
> +type Storage interface {
Интерфейсы как и типы струтур тоже нужно комментировать

2022-07-10 06:18 UTC, bambruysk commented on internal/api/api.go
> +	a.router.POST("/", a.CrShort())
а мы же можем сюда передавать сам хендлер

2022-07-10 06:18 UTC, bambruysk commented on internal/api/api.go
> +func (a *api) CrShort() gin.HandlerFunc {
Если роутер передавать просто хендрел то можно просто
func (a *api) CrShort(c *gin.Context) {

2022-07-10 06:18 UTC, bambruysk commented on internal/urlstorage/urlstorage.go
> +func (st *storage) GetByID(id string) *string {
не надо возвращать указатель на строку - можно просто строку. Строки в Go иммутабльные - и компилятор их хорошо оптимизирует.

2022-07-10 06:18 UTC, bambruysk commented on internal/urlstorage/urlstorage.go
> +	if _, fd := st.data[id]; fd {
Здесь тоже добавить st.mtx.Rlock()/RUnlock() -  будет блокироваться чтение на время записи.

2022-07-10 08:51 UTC, icyrogue commented on internal/api/api.go
> +type URLProcessor interface {
Используется, чтобы создать короткий url с помощью бизнес логики в POST хендлере
```go
	url, err := a.urlProc.CreateShortURL(string(req))
		if err != nil {
			c.String(http.StatusInternalServerError, err.Error())
			return
		}
		c.String(http.StatusCreated, a.opts.Hostname+"/"+url) 
```

2022-07-10 09:28 UTC, bambruysk commented on internal/api/api.go
> +type URLProcessor interface {
ок

2022-07-10 09:33 UTC, bambruysk requested changes

2022-07-10 09:33 UTC, bambruysk commented on internal/urlstorage/urlstorage.go
> +	if _, fd := st.data[id]; fd {
Мютекс типа RWMutex -  для работы с чтением нужно использовать RLock

2022-07-10 09:33 UTC, bambruysk commented on internal/urlstorage/urlstorage.go
> +	return ""
Здесь нужно возвразать дополнительный параметр типа error или bool, который показывает была ли найдена запись - это достаточно идиоматично.

2022-07-10 09:36 UTC, bambruysk commented on internal/idgen/genid.go
> +func InitID() {
Эту инициализацию можно перенести в func init() -тогда она будет выполнятся автоматически при импорте пакета.  И не нужно будет тащить его в мейн

2022-07-10 11:42 UTC, bambruysk approved these changes

2022-07-10 11:43 UTC, bambruysk approved these changes
Можно сливать

2022-07-10 11:45 UTC, bambruysk commented
Можно мержить

2022-07-10 15:40 UTC, merged